
name: 'acme_standard_data_transformation_framework'
version: '1.0.0'
config-version: 2


profile: 'default'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:      
  - "target"
  - "dbt_packages"

vars:

  salesforce_database_name:
  salesforce_schema_name:
  salesforce_opportunites_table_name:
  salesforce_accounts_table_name:
  salesforce_contacts_table_name:
  salesforce_leads_table_name:



models:
  acme_standard_data_transformation_framework:
